#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action

main() {
    action=$1
    shift

    case $action in
        help|list|show)
            help_for_${action}
            ;;
        ?*)
            echo "${cw_BINNAME}: no such topic: ${action}"
            echo ""
            general_help
            ;;
        *)
            general_help
            ;;
    esac
}

help_for_list() {
    cat <<EOF
  SYNOPSIS:

    alces howto list

  DESCRIPTION:

    Display an indexed list of available how to guide names.

EOF
}

help_for_show() {
    cat <<EOF
  SYNOPSIS:

    alces howto show <index|name>
    alces howto <index|name>

  DESCRIPTION:

    Display the how to guide with <index> or <name>.

    If you are using an X11 environment and have the "evince" tool
    available, guides will be shown in a separate application.
    Otherwise guides will be shown using the default "man page" style.

EOF
}

help_for_help() {
    cat <<EOF
  SYNOPSIS:

    alces howto help [<command>]

  DESCRIPTION:

    Get help with howto commands.  If no <command> is specified, show
    some general help.

EOF
}

general_help() {
    local binname
    binname="${cw_BINNAME% *}"
    cat <<EOF
  NAME:

    ${binname}

  DESCRIPTION:

    Helpful guides on how to use your research environment.

  COMMANDS:

EOF
printf "    %-24s  %s\n" "$binname help" "More help about this command."
printf "    %-24s  %s\n" "$binname list" "List available guides."
printf "    %-24s  %s\n" "$binname show" "Display a guide."
printf "    %-24s  %s\n" "$binname <index|name>" "Display a guide."
cat <<EOF

Please report bugs to support@alces-software.com
Alces Software home page: <http://alces-software.com>
EOF
}

main "$@"
