#==============================================================================
# Copyright (C) 2007-2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
source 'http://rubygems.org'
#source 'http://gems.alces-software.com'

gem 'alces-tools', '>= 0.13.0'
gem 'commander'
gem 'terminal-table'
gem 'grit'
gem 'dm-rest-adapter', '1.3.0.alces0'
gem 'rubytree'
gem 'dm-sqlite-adapter', '>= 1.2.0'
gem 'dm-migrations', '>= 1.2.0'
gem 'dm-aggregates', '>= 1.2.0'
gem 'memoist'
gem 'ronn'

# Test gems - TODO not always install?
gem 'minitest'
