#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require handler

main() {
    local a b c handlername reponame with_hooks enabled
    if [ "$1" == "--with-hooks" ]; then
        with_hooks=true
        shift
    fi
    for a in "${cw_HANDLER_REPODIR}"/*; do
        reponame=$(basename "$a")
        for b in "${a}"/*; do
            handlername="$(basename "$b")"
            if handler_is_enabled "${handlername}"; then
                enabled='*'
            else
                enabled=' '
            fi
            if [ "$with_hooks" ]; then
                handlername="$(basename "$b")"
                for c in "${b}"/*; do
                    if [ "$(basename "$c")" != "metadata.yml" ]; then
                        echo -e "[${enabled}] \e[38;5;68m${reponame}\e[0m/\e[38;5;221m${handlername}\e[0m/\e[35m$(basename "$c")\e[0m"
                    fi
                done
            else
                echo -e "[${enabled}] \e[38;5;68m${reponame}\e[0m/\e[38;5;221m$(basename "$b")\e[0m"
            fi
        done
    done
    action_cleanup
}

main "$@"
