#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action

main() {
    action=$1
    shift

    case $action in
        help|avail|enable|disable|update)
            help_for_${action}
            ;;
        ?*)
            echo "${cw_BINNAME}: no such topic: ${action}"
            echo ""
            general_help
            ;;
        *)
            general_help
            ;;
    esac
}

help_for_avail() {
    cat <<EOF
  SYNOPSIS:

    alces handler avail [OPTIONS]

  DESCRIPTION:

    Display available handlers.  Handlers that are currently enabled
    are marked with a '*'.

  OPTIONS:

    --with-hooks
      Also show what hooks each handler provides.

EOF
}

help_for_disable() {
    cat <<EOF
  SYNOPSIS:

    alces handler disable <handler>

  DESCRIPTION:

    Remove a previously enabled <handler>, disabling all associated
    hooks.

EOF
}

help_for_enable() {
    cat <<EOF
  SYNOPSIS:

    alces handler enable [<repository>/]<handler> [PARAMS...]

  DESCRIPTION:

    Enable an available <handler> and make its hooks available for
    use.

    Any supplied PARAMS will be passed on to the handler installation
    script (check handler documentation for information on what
    installation parameters a handler accepts).

    If you have multiple repositories available which contained
    similarly named handlers, you may specify a <repository>.  If no
    repository is specified, the 'base' repository is used by default.

    Using this command will execute installation instructions
    associated with the handler if any are present.

EOF
}

help_for_help() {
    cat <<EOF
  SYNOPSIS:

    alces handler help [<command>]

  DESCRIPTION:

    Get help with handler commands.  If no <command> is specified,
    show some general help.

EOF
}

help_for_update() {
    cat <<EOF
  SYNOPSIS:

    alces handler update [<repository> <url>]

  DESCRIPTION:

    Initialize or update a handler repository.

    If a <repository> and <url> are specified, create or update the
    named <repository> from the specified remote git repository <url>.

    If no parameters are specified, initialize or update the 'base'
    repository from a default URL.

EOF
}

general_help() {
    local binname
    binname="${cw_BINNAME% *}"
    cat <<EOF
  NAME:

    ${binname}

  DESCRIPTION:

    Install and manage node handlers.

  COMMANDS:

EOF
printf "    %-22s  %s\n" "$binname help" "More help about this command."
printf "    %-22s  %s\n" "$binname avail" "List installed/available handlers."
printf "    %-22s  %s\n" "$binname enable" "Enable a handler from a repository."
printf "    %-22s  %s\n" "$binname disable" "Disable a handler."
printf "    %-22s  %s\n" "$binname update" "Update handler repository."
cat <<EOF

Please report bugs to support@alces-software.com
Alces Software home page: <http://alces-software.com>
EOF
}

main "$@"
