#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require storage
require process
require distro

main() {
    local type repo
    type="$1"
    shift
    if [[ $type == *"/"* ]]; then
        repo="${type%%/*}"
        type="${type#*/}"
    else
        repo="${cw_STORAGE_DEFAULT_REPO}"
    fi

    if [ -z "$type" ]; then
        action_die "storage type not specified"
    elif ! storage_repo_exists "${repo}"; then
        action_die "storage type repository was not found: $repo"
    elif ! storage_exists "${repo}/${type}"; then
        action_die "storage type not found: $repo/$type"
    elif storage_is_enabled "${type}"; then
        action_die "storage type already enabled: ${type}"
    fi
    if storage_install "${repo}/${type}" "${cw_DIST}" "$@"; then
        storage_enable "${repo}/${type}"
        action_die "enabled storage type: ${repo}/${type} -> ${type}" 0
    else
        action_die "unable to enable storage type: ${repo}/${type}" 1
    fi
}

process_reexec_sudo "$@"
main "$@"
