#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require storage
require process

main() {
    local name system
    if [ "$1" == "--system" ]; then
        process_reexec_sudo "$@"
        system="$1"
        shift
    fi
    name="$1"
    if [ -z "${name}" ]; then
        action_die "please supply storage configuration name"
    else
        if storage_forget_configuration ${system} "${name}"; then
            action_die "storage configuration forgotten" 0
        else
            action_die "no storage configuration found for '${name}'"
        fi
    fi
    action_cleanup
}

main "$@"
