#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require storage

main() {
    local cmd name type result
    cmd="$1"
    shift
    case $cmd in
        get|put|mkbucket|rmbucket|rm|addbucket)
            cw_BINNAME="${cw_BINNAME% *} ${cmd}"
            ;;
        *)
            action_die "invalid command supplied: $cmd"
            ;;
    esac
    if [ "$1" == "-n" ]; then
        name="$2"
        shift 2
    else
        name="$(storage_default_configuration)"
    fi

    if [ -z "${name}" ]; then
        action_die "please supply storage configuration name"
    elif storage_configuration_exists "${name}"; then
        type=$(storage_type_for "${name}")
        if storage_load_functions "${type}"; then
            ${type}_storage_${cmd} "${name}" "$@" | stdbuf -oL sed -e "s/^/$cw_BINNAME: /g"
            action_exit $?
        else
            action_die "storage type not available or not enabled: ${type}"
        fi
    else
        action_die "storage configuration not found: ${name}"
    fi
    action_cleanup
}

main "$@"
