#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require storage

_show_config() {
    local path name type default
    path="$1"
    name="$(basename "${path}" | cut -f1 -d'.')"
    type="$(basename "${path}" | cut -f2 -d'.')"
    if [ "$(storage_default_configuration)" == "${name}" ]; then
        default="*"
    else
        default=" "
    fi
    echo -e "[$default] \e[38;5;${cw_THEME_mid}m${name}\e[0m (\e[38;5;${cw_THEME_sec2}m${type}\e[0m)"
}

main() {
    if ! storage_each_configuration "_show_config"; then
        action_die "no storage configurations found"
    fi
    action_cleanup
}

main "$@"
