#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require files
require process

_can_autoscale() {
    "${_AWS}" --region "${cw_INSTANCE_aws_region}" \
              autoscaling describe-auto-scaling-groups &>/dev/null
}

main() {
    local operation
    operation="$1"
    if files_load_config --optional instance-aws config/cluster; then
        if _can_autoscale; then
            if [ -z "$operation" -o "$operation" == "status" ]; then
                echo "Autoscaling: ${cw_INSTANCE_aws_autoscaling}"
            elif [ "$operation" == "enable" ]; then
                if [ "${cw_INSTANCE_aws_autoscaling}" == "disabled" ]; then
                    sed -i -e 's/^cw_INSTANCE_aws_autoscaling=.*/cw_INSTANCE_aws_autoscaling=enabled/' \
                        "${cw_ROOT}"/etc/config/cluster/instance-aws.rc
                    action_die "autoscaling enabled" 0
                else
                    action_die "autoscaling already enabled" 0
                fi
            elif [ "$operation" == "disable" ]; then
                if [ "${cw_INSTANCE_aws_autoscaling}" == "enabled" ]; then
                    sed -i -e 's/^cw_INSTANCE_aws_autoscaling=.*/cw_INSTANCE_aws_autoscaling=disabled/' \
                        "${cw_ROOT}"/etc/config/cluster/instance-aws.rc
                    action_die "autoscaling disabled" 0
                else
                    action_die "autoscaling already disabled" 0
                fi
            else
                action_die "unrecognized operation: $operation"
            fi
        elif [ "$operation" == "status" ]; then
            echo "Autoscaling: not available"
        else
            action_die "autoscaling not available for this cluster"
        fi
    elif [ "$operation" == "status" ]; then
        echo "Autoscaling: not available"
    else
        action_die "autoscaling not available on this platform"
    fi
}

if [ -n "$1" -a "$1" != "status" ]; then
    process_reexec_sudo "$@"
fi

_AWS="${cw_ROOT}"/opt/aws/bin/aws

main "$@"
