#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action

main() {
    action=$1
    shift

    case $action in
        help|node|autoscaling|hyperthreading|scheduler|thp|clocksource)
            help_for_${action}
            ;;
        ?*)
            echo "${cw_BINNAME}: no such topic: ${action}"
            echo ""
            general_help
            ;;
        *)
            general_help
            ;;
    esac
}

general_help() {
    local binname
    binname="${cw_BINNAME% *}"
    cat <<EOF
  NAME:

    ${binname}

  DESCRIPTION:

    Perform configuration tasks.

  COMMANDS:

EOF
printf "    %-30s  %s\n" "$binname help" "More help about this command."
printf "    %-30s  %s\n" "$binname node" "Perform initial node setup."
printf "    %-30s  %s\n" "$binname autoscaling" "Control autoscaling behaviour."
printf "    %-30s  %s\n" "$binname hyperthreading" "Control hyperthreading behaviour."
printf "    %-30s  %s\n" "$binname thp" "Control transparent hugepages behaviour."
printf "    %-30s  %s\n" "$binname clocksource" "Control clocksource behaviour."
cat <<EOF

Please report bugs to support@alces-software.com
Alces Software home page: <http://alces-software.com>
EOF
}

help_for_node() {
    cat <<EOF
  SYNOPSIS:

    alces configure node

  DESCRIPTION:

    Perform initial node configuration.

EOF
}

help_for_autoscaling() {
    cat <<EOF
  SYNOPSIS:

    alces configure autoscaling [enable|disable|status]

  DESCRIPTION:

    Change or retrieve autoscaling behaviour.  If no action is
    specified, display autoscaling status.

EOF
}

help_for_hyperthreading() {
    cat <<EOF
  SYNOPSIS:

    alces configure hyperthreading [enable|disable|status]

  DESCRIPTION:

    Change or retrieve hyperthreading behaviour.  If no action is
    specified, display hyperthreading status.

EOF
}

help_for_scheduler() {
    cat <<EOF
  SYNOPSIS:

    alces configure scheduler [status]
    alces configure scheduler allocation <strategy>
    alces configure scheduler submission <strategy>

  DESCRIPTION:

    Change or retrieve scheduler behaviour.  If no action is
    specified, display current scheduler configuration.

    Valid 'allocation' strategies are 'packing' (pack jobs on to as
    few nodes as possible) or 'spanning' (select the least busy nodes
    for jobs).

    Valid 'submission' strategies are 'all' (accept job submission
    from all nodes) 'master' (accept job submission from the master
    node only) or 'none' (disable job submission).

EOF
}

help_for_help() {
    cat <<EOF
  SYNOPSIS:

    alces configure help [<command>]

  DESCRIPTION:

    Get help with configure commands.  If no <command> is specified,
    show some general help.

EOF
}

help_for_thp() {
  cat <<EOF
  SYNOPSIS:

    alces configure thp [enable|disable|status]

  DESCRIPTION:

    Change or retrieve transparent hugepages behaviour.  If no action is
    specified, display transparent hugepages status.

EOF
}

help_for_clocksource() {
  local sources
  sources=$(cat /sys/devices/system/clocksource/clocksource0/available_clocksource)
  sources=$(echo $sources | xargs echo -n | tr " " "|")
  cat <<EOF
  SYNOPSIS:

    alces configure clocksource [default|$sources]

  DESCRIPTION:

    Change or retrieve the clocksource.  If no action is
    specified, lists the current and available clocksources.

    The 'default' action resets the clocksource to the system default.

    Changes on the master node are reflected cluster wide.

EOF
}

main "$@"
