#!/bin/bash
#==============================================================================
# Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require process

main() {
	local cmd
	cmd=$1
	shift

	case $cmd in
		enable|always)
			echo always > /sys/kernel/mm/transparent_hugepage/enabled
			;;
		disable|never)
			echo never > /sys/kernel/mm/transparent_hugepage/enabled
			;;
		""|status)
			status=$(cat /sys/kernel/mm/transparent_hugepage/enabled)
			case $status in
				\[always\]*)
					echo "enabled"
					;;
				*\[never\])
					echo "disabled"
					;;
				*)
					action_die "unrecognised status: $status"
			esac
			;;
		*)
			action_die "unrecognised operation: $cmd"
	esac
}

if [ -n "$1" -a "$1" != "status" ]; then
	process_reexec_sudo "$@"
fi
main "$@"
