#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
if [ "$1" == "--short" ]; then
    short=true
    shift
fi

cluster="$1"
version="$2"
distro="$3"

w=79

emit() {
  printf "%*s\n" $(((${#1}+${w})/2)) "$1"
}

if [ "$short" ]; then
    echo "<<< Alces Clusterware (v${version}) >>>"
else
    emit '+++++++++++++++++++++++++++++++++++++++++++++'
    emit "Welcome to $cluster"
    emit "Alces Clusterware (v$version)"
    emit "Based on $distro"
    emit '+++++++++++++++++++++++++++++++++++++++++++++'
fi
