#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.vars.sh ]; then
            source "${a}"/clusterware/config.vars.sh
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

_emit() {
    local w=79
    printf "%*s\n" $(((${#1}+${w})/2)) "$1"
}

main() {
    if [ "$1" == "enable" ]; then
	files_load_config clusterware
        _emit '+++++++++++++++++++++++++++++++++++++++++++++' > /etc/nologin
        _emit "Alces Clusterware (r${cw_RELEASE:-1})" >> /etc/nologin
	if distro_is el6 || distro_is el7; then
            _emit "Based on $(sed 's/\(.*\) release \(.*\) .*/\1 \2/g' /etc/redhat-release)" >> /etc/nologin
	fi
        _emit '+++++++++++++++++++++++++++++++++++++++++++++' >> /etc/nologin
        echo >> /etc/nologin
	_emit 'This node is being prepared.' >> /etc/nologin
	cat <<EOF >> /etc/nologin

This node is currently being configured and is not yet operational.  Please
try again in a few minutes.  If you continue to see this message, please
contact the cluster administrator.
EOF
    else
	rm -f /etc/nologin
    fi
}

setup

require distro
require files

main "$@"
