#!/bin/bash

main() {
    local name domainname short_name ip tmpfile includes_fqdn
    if [ "$1" == "--includes-fqdn" ]; then
	includes_fqdn=true
	shift
    fi
    
    name="$1"
    ip="$2"

    if [ "$includes_fqdn" ]; then
	short_name=$(echo ${name} | cut -f1 -d'.')
    else
	domainname="$(hostname -d)"
	if [[ "${name}" != *"."* ]]; then
	    # name is simply "<hostname>"
	    short_name="${name}"
	    name="${name}.${domainname}"
	else
	    if [[ "${name}" != *".${domainname}" ]]; then
		# name is "<hostname>.<subdomain>"
		name="$1.${domainname}"
	    fi
	    short_name=$(echo ${name} | cut -f1 -d'.')
	fi
    fi

    tmpfile="$(mktemp /tmp/update-etc-hosts.XXXXXXXX)"

    if ! grep -q "^${ip}\b.*\b${name}\b" /etc/hosts; then
	# no applicable entry yet.
	if grep -q "^${ip}\b" /etc/hosts; then
            # IP present, but not this name: sed
	    echo "Adding to existing /etc/hosts entry for ${ip}: ${name} -> ${ip}"
            sed -e "s/^${ip} \(.*\)/${ip} ${name} ${short_name} \1/g" -i /etc/hosts
	elif grep -q "\s\b${name}\b" /etc/hosts; then
            # name present, but not this IP: sed out the existing name
	    echo "Replacing existing /etc/hosts entry for ${name}: ${name} -> ${ip}"
            sed -re "s/^(.*)\s\b${name}\b(.*)/\1 \2/g" /etc/hosts | \
		sed -re "s/^(.*)\s\b${short_name}\b(.*)/\1 \2/g" | \
		egrep -v "^(\S+)\s*$" > "${tmpfile}"
            cat "${tmpfile}" > /etc/hosts
            echo "${ip} ${name} ${short_name}" >> /etc/hosts
	else
            # IP and name not present, just add
	    echo "Adding new /etc/hosts entry: ${name} -> ${ip}"
            echo "${ip} ${name} ${short_name}" >> /etc/hosts
	fi
    else
	echo "Already exists in /etc/hosts: ${name} -> ${ip}"
    fi

    rm -f "${tmpfile}"
}

main "$@"
