#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require document

main() {
    local idx template target source_name
    idx="$1"
    target="$2"
    if [ -z "$target" ]; then
        action_die "no target supplied - please supply both template number and target file name."
    fi
    if template="$(document_get "$idx" templates .tpl .sh.tpl)"; then
        if [ -d "${target}" ]; then
            target="${target}/$(basename "${source}" .tpl)"
        fi
        if [ -f "${target}" ]; then
            action_die "file already exists at target location '${target}'"
        fi
        source_name="$(basename "${template}" .tpl)"
        if _template_render "${template}" > "${target}"; then
            chmod 755 "${target}"
            action_die "template '$(basename "${source_name}" .sh)' copied to '${target}'" 0
        else
            action_die "failed to copy template '$(basename "${source_name}" .sh)' to '${target}'"
        fi
    else
        errlvl=$?
        if [ $errlvl == 1 ]; then
            action_die "no templates found"
        elif [ $errlvl == 3 ]; then
            action_die "please specify a template index or name"
        else
            action_die "invalid template number requested: ${idx}"
        fi
    fi
    action_cleanup
}

. "${cw_ROOT}/libexec/template/share/functions.sh"

main "$@"
