#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action

main() {
    action=$1
    shift

    case $action in
        help|list|show|copy|info)
            help_for_${action}
            ;;
        ?*)
            echo "${cw_BINNAME}: no such topic: ${action}"
            echo ""
            general_help
            ;;
        *)
            general_help
            ;;
    esac
}

help_for_copy() {
    cat <<EOF
  SYNOPSIS:

    alces template copy <index|name> <target>

  DESCRIPTION:

    Copy the template with <index> or <name> to the file or directory
    given by <target>.  Once you've copied a template you can
    customize and submit it to a job scheduler.

EOF
}

help_for_info() {
    cat <<EOF
  SYNOPSIS:

    alces template info <index|name>

  DESCRIPTION:

    Display any accompanying documentation for the template with
    <index> or <name>.

    Accompanying documentation may provide further information on when
    you should select a certain template and how it can be customized.

EOF
}

help_for_list() {
    cat <<EOF
  SYNOPSIS:

    alces template list

  DESCRIPTION:

    Display an indexed list of available job script template names.

EOF
}

help_for_show() {
    cat <<EOF
  SYNOPSIS:

    alces template show <index|name>

  DESCRIPTION:

    Display the job script template with <index> or <name>.

EOF
}

help_for_help() {
    cat <<EOF
  SYNOPSIS:

    alces template help [<command>]

  DESCRIPTION:

    Get help with template commands.  If no <command> is specified,
    show some general help.

EOF
}

general_help() {
    local binname
    binname="${cw_BINNAME% *}"
    cat <<EOF
  NAME:

    ${binname}

  DESCRIPTION:

    Job script templates tailored to your research environment.

  COMMANDS:

EOF
printf "    %-22s  %s\n" "$binname help" "More help about this command."
printf "    %-22s  %s\n" "$binname list" "List available templates."
printf "    %-22s  %s\n" "$binname info" "Display information about a template."
printf "    %-22s  %s\n" "$binname show" "Display a template."
printf "    %-22s  %s\n" "$binname copy" "Copy a template for your use."
cat <<EOF

Please report bugs to support@alces-software.com
Alces Software home page: <http://alces-software.com>
EOF
}

main "$@"
