#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require document

main() {
    local idx template source_name
    idx="$1"
    if template="$(document_get $idx templates .tpl .sh.tpl)"; then
        source_name="$(basename "${template}" .tpl)"
        if [ -f "$(dirname "${template}")/${source_name}.md" ]; then
            document_show "$(dirname "${template}")/${source_name}.md" "Alces Clusterware Templates"
        else
            action_die "no information available for template '$(basename "${source_name}" .sh)'"
        fi
    else
        if [ $? == 1 ]; then
            action_die "no templates found"
        else
            action_die "invalid template number requested: ${idx}"
        fi
    fi
    action_cleanup
}

main "$@"
