#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require document

main() {
    local idx template source_name vars license
    idx="$1"
    if template="$(document_get "$idx" templates .tpl .sh.tpl)"; then
        source_name="$(basename "${template}" .tpl)"
        if [ -f "$(dirname "${template}")/${source_name}.md" ]; then
            document_show "$(dirname "${template}")/${source_name}.md" "Alces Clusterware Templates"
        else
            vars=$(grep '^#@ ' "${template}" | cut -c4-)
            if [ "$vars" ]; then
                declare -A cw_TEMPLATE
                eval "$vars"
                if [ "${cw_TEMPLATE[license]}" ]; then
                    license=$(cat <<EOF
## LICENSE

This work is licensed under a ${cw_TEMPLATE[license]} License.

EOF
                )
                fi
                cat <<EOF | document_show "-" "Alces Clusterware Templates"
# $(basename "${source_name}" .sh)(7) -- ${cw_TEMPLATE[name]}

## DESCRIPTION

${cw_TEMPLATE[desc]}

${cw_TEMPLATE[extended_desc]}

${license}

## COPYRIGHT

${cw_TEMPLATE[copyright]}

EOF
            else
                action_die "no information available for template '$(basename "${source_name}" .sh)'"
            fi
        fi
    else
        errlvl=$?
        if [ $errlvl == 1 ]; then
            action_die "no templates found"
        elif [ $errlvl == 3 ]; then
            action_die "please specify a template index or name"
        else
            action_die "invalid template number requested: ${idx}"
        fi
    fi
    action_cleanup
}

main "$@"
