#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require document

main() {
    local a c tmpls tmpl vars namepart w
    if tmpls=($(document_list templates .tpl)); then
        c=0
        w=0
        for a in "${tmpls[@]}"; do
            tmpl="$(basename "$(basename "${a}" .tpl)" .sh | sed 's/^[0-9]*-\(.*\)/\1/g')"
            if [ "${#tmpl}" -gt "${w}" ]; then
                w="${#tmpl}"
            fi
        done
        for a in "${tmpls[@]}"; do
            c=$(($c+1))
            tmpl="$(basename "$(basename "${a}" .tpl)" .sh | sed 's/^[0-9]*-\(.*\)/\1/g')"
            vars=$(grep '^#@ ' "${a}" | cut -c4-)
            if [ "$vars" ]; then
                declare -A cw_TEMPLATE
                eval "$vars"
            fi
            if [ "${cw_TEMPLATE[name]}" ]; then
                namepart=" ... \e[38;5;${cw_THEME_prim}m${cw_TEMPLATE[name]}\e[0m"
            fi
            echo -e "\e[38;5;${cw_THEME_sec1}m$(printf "%2d" ${c})\e[0m -> \e[38;5;${cw_THEME_sec2}m$(printf "%-${w}s" ${tmpl})\e[0m${namepart}"
            unset cw_TEMPLATE namepart
        done
    else
        action_die "no templates found"
    fi
    action_cleanup
}

main "$@"
