#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require serviceware

main() {
    local a b c service reponame enabled installed
    if [ "$1" == "--components" ]; then
        with_components=true
        shift
    fi
    for a in "${cw_SERVICEWARE_REPODIR}"/*; do
        reponame=$(basename "$a")
        for b in "${a}"/*; do
            service="$(basename "$b")"
            if [ "${with_components}" ]; then
                if serviceware_is_installed "${service}"; then
                    installed='*'
                    for c in $(serviceware_list_components "${reponame}/${service}"); do
                        if ! serviceware_is_enabled "${service}-${c}"; then
                            installed=' '
                        fi
                        echo -e "[${installed}] \e[38;5;68m${reponame}\e[0m/\e[38;5;221m$(basename "$b")\e[0m/\e[35m${c}\e[0m"
                    done
                fi
            else
                if serviceware_is_installed "${service}"; then
                    installed='*'
                else
                    installed=' '
                fi
                echo -e "[${installed}] \e[38;5;68m${reponame}\e[0m/\e[38;5;221m$(basename "$b")\e[0m"
            fi
        done
    done
    action_cleanup
}

main "$@"
