#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action

main() {
    action=$1
    shift

    case $action in
        help|avail|enable|install|update)
            help_for_${action}
            ;;
        ?*)
            echo "${cw_BINNAME}: no such topic: ${action}"
            echo ""
            general_help
            ;;
        *)
            general_help
            ;;
    esac
}

help_for_avail() {
    cat <<EOF
  SYNOPSIS:

    alces service avail

  DESCRIPTION:

    Display services that are available for installation.  Services
    that are currently installed are marked with a '*'.

EOF
}

help_for_install() {
    cat <<EOF
  SYNOPSIS:

    alces service install [<repository>/]<service> [PARAMS...]

  DESCRIPTION:

    Install an available <service> and allow its components to be
    enabled.

    Any supplied PARAMS will be passed on to the component
    configuration script (check service documentation for information
    on what configuration parameters a component accepts).

    If you have multiple repositories available which contained
    similarly named services, you may specify a <repository>.  If no
    repository is specified, the 'base' repository is used by default.

    Using this command will execute installation instructions
    associated with the service.

EOF
}

help_for_enable() {
    cat <<EOF
  SYNOPSIS:

    alces service enable [<repository>/]<service>[/<component>] [PARAMS...]

  DESCRIPTION:

    Enable a <component> for a previously installed <service>.  If no
    component is specified, the 'base' component is used by default.
    If no repository is specified, the 'base' repository is used by
    default.

    Any supplied PARAMS will be passed on to the component
    configuration script (check service documentation for information
    on what configuration parameters a component accepts).

    Using this command will execute installation/configuration
    instructions associated with the component.

EOF
}

help_for_help() {
    cat <<EOF
  SYNOPSIS:

    alces service help [<command>]

  DESCRIPTION:

    Get help with service commands.  If no <command> is specified,
    show some general help.

EOF
}

help_for_update() {
    cat <<EOF
  SYNOPSIS:

    alces service update [<repository> <url>]

  DESCRIPTION:

    Initialize or update a service repository.

    If a <repository> and <url> are specified, create or update the
    named <repository> from the specified remote git repository <url>.

    If no parameters are specified, initialize or update the 'base'
    repository from a default URL.

EOF
}

general_help() {
    local binname
    binname="${cw_BINNAME% *}"
    cat <<EOF
  NAME:

    ${binname}

  DESCRIPTION:

    Install and manage serviceware.

  COMMANDS:

EOF
printf "  %-22s  %s\n" "$binname help" "More help about this command."
printf "  %-22s  %s\n" "$binname avail" "List installed/available serviceware."
printf "  %-22s  %s\n" "$binname enable" "Enable a serviceware component."
printf "  %-22s  %s\n" "$binname install" "Install serviceware from a repository."
printf "  %-22s  %s\n" "$binname update" "Update serviceware repository."
cat <<EOF

Please report bugs to support@alces-software.com
Alces Software home page: <http://alces-software.com>
EOF
}

main "$@"
