#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require serviceware
require process

main() {
    local service repo
    service="$1"
    if [[ $service == *"/"* ]]; then
        repo="${service%%/*}"
        service="${service#*/}"
    else
        repo="${cw_SERVICEWARE_DEFAULT_REPO}"
    fi

    if [ -z "$service" ]; then
        action_die "service not specified"
    elif ! serviceware_repo_exists "${repo}"; then
        action_die "serviceware repository was not found: $repo"
    elif ! serviceware_exists "${repo}/${service}"; then
        action_die "service not found: $repo/$service"
    elif serviceware_is_installed "${service}"; then
        action_die "service already installed: ${service}"
    fi
    if serviceware_install "${repo}/${service}" "${cw_DIST}"; then
        action_die "installed serviceware: ${repo}/${service} -> ${service}" 0
    else
        action_die "serviceware could not be installed: ${repo}/${service}" 1
    fi
}

process_reexec_sudo "$@"
main "$@"
