#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action

# Action to package built serviceware for uploading to S3.
# Note: This action currently has the limitation that it will only package
# Serviceware that is self-contained within a directory in "$cw_ROOT/opt/", so
# e.g. Slurm which consists of "$cw_ROOT/opt/{slurm,munge}" will not be
# correctly packaged by this.

# TODO: This action could do with some autocompletion.

main() {
    local service
    service="$1"
    if [ -z "$service" ]; then
        action_die "service not specified"
    fi
    tarball="/tmp/${service}.tar.gz"

    if (cd "${cw_ROOT}" && tar -zcvf "${tarball}" "opt/${service}"); then
        action_die "packaged ${tarball}"
    else
        action_die "could not package ${service}"
    fi
}

main "$@"
