#!/bin/bash
#==============================================================================
# Copyright (C) 2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
if (( UID != 0 )); then
  echo "$0: must run as root"
  exit 1
fi

if [ -z "$alces_OS" ]; then
  echo "$0: must set alces_OS variable (current options are: 'el6', 'el7')"
  exit 1
fi

# XXX - requires curl, tar -- check here

# set alces_SOURCE to either 'fresh' or 'dist'
#  'fresh' -- build all dependencies
#  'dist'  -- download prebuilt dependencies
alces_SOURCE="${alces_SOURCE:-fresh}"

src_dir="${alces_SRC_DIR:-$(mktemp -d clusterware.XXXXXXXX)}"

if [ ! -f "${src_dir}"/scripts/install ]; then
    src_url_base="https://github.com/alces-software/clusterware/archive"
    src_url_file="${alces_SOURCE_BRANCH:-master}.tar.gz"
    src_url="${alces_SOURCE_URL:-${src_url_base}/${src_url_file}}"
    # Download source
    cat <<EOF
[33m
===============================================================================
 DOWNLOADING SOURCE
===============================================================================
[0m
EOF
    mkdir -p "${src_dir}"
    curl -L "${src_url}" | \
        tar -C "${src_dir}" --strip-components 1 -xz

    if [ $? -gt 0 ]; then
        echo "Unable to retrieve clusterware source, aborting."
        exit 1
    fi
fi

cat <<EOF
[33m
===============================================================================
 BOOTSTRAPPING INSTALLER
===============================================================================
[0m
EOF
bash "${src_dir}/scripts/install" "$alces_OS" "$alces_SOURCE"
