#!/bin/bash
#==============================================================================
# Copyright (C) 2015-2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
if (( UID != 0 )); then
  echo "$0: must run as root"
  exit 1
fi

if [ -z "$cw_DIST" ]; then
  echo "$0: must set cw_DIST variable (current options are: 'el6', 'el7')"
  exit 1
fi

if [ -z "${cw_BUILD_noninteractive}" ]; then
    progress="-#"
else
    progress=""
fi

# Configuration parameters for isolated network propagation
#cw_BUILD_app_manager_address=""
#export cw_BUILD_source_url=""
#export cw_BUILD_dist_url=""
#export cw_BUILD_repos_url=""

# set cw_BUILD_fetch_handling to either 'source' or 'bin'
#  'source' -- build all dependencies
#  'bin'    -- download prebuilt dependencies
cw_BUILD_fetch_handling="${cw_BUILD_fetch_handling:-bin}"

src_dir="${cw_BUILD_source_dir:-$(mktemp -d /tmp/clusterware.XXXXXXXX)}"

if [ ! -f "${src_dir}"/scripts/install ]; then
    if [ "$(ls -A "${src_dir}" 2>/dev/null)" ]; then
        echo "An incomplete source directory already exists, please remove or specify a different location: ${src_dir}"
        exit 1
    fi
    cleanup=true
    src_url_base="https://github.com/alces-software/clusterware/archive"
    src_url_file="${cw_BUILD_source_branch:-master}.tar.gz"
    src_url="${cw_BUILD_source_url:-${src_url_base}/${src_url_file}}"
    # Download source
    cat <<EOF
[33m
===============================================================================
 DOWNLOADING SOURCE
===============================================================================
[0m
EOF
    mkdir -p "${src_dir}"
    curl ${progress} -L "${src_url}" | \
        tar -C "${src_dir}" --strip-components 1 -xz

    if [ $? -gt 0 ]; then
        echo "Unable to retrieve Alces Clusterware source tree, aborting."
        exit 1
    fi

    if [ "$cw_BUILD_repos_url" ]; then
        curl ${progress} -L "${cw_BUILD_repos_url}/clusterware-handlers.tar.gz" > "${src_dir}/clusterware-handlers.tar.gz"
        curl ${progress} -L "${cw_BUILD_repos_url}/clusterware-sessions.tar.gz" > "${src_dir}/clusterware-sessions.tar.gz"
        curl ${progress} -L "${cw_BUILD_repos_url}/clusterware-services.tar.gz" > "${src_dir}/clusterware-services.tar.gz"
        curl ${progress} -L "${cw_BUILD_repos_url}/clusterware-storage.tar.gz" > "${src_dir}/clusterware-storage.tar.gz"
        curl ${progress} -L "${cw_BUILD_repos_url}/packager-base.tar.gz" > "${src_dir}/packager-base.tar.gz"
    fi
fi

cat <<EOF
[33m
===============================================================================
 BOOTSTRAPPING INSTALLER
===============================================================================
[0m
EOF
bash "${src_dir}/scripts/install" "$cw_DIST" "$cw_BUILD_fetch_handling"
if [ "$cleanup" = "true" ]; then
    rm -rf "${src_dir}"
fi
