#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.rc ]; then
            source "${a}"/clusterware/config.rc
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
    local target confirm
    target="$1"
    cfg_file="$(xdg_config_home)"/clusterware/sync.${target}.yml
    if [ -z "$target" ]; then
        action_die "usage: ${cw_BINNAME} <target name>"
    elif [ -f "${cfg_file}" ]; then
        while [ "$confirm" != "y" -a "$confirm" != "n" ]; do
            read -p "Remove sync configuration for '${target}' (Y/N)? " -n1 confirm
            echo ""
            confirm="$(echo "${confirm}" | tr '[A-Z]' '[a-z]')"
        done
        if [ "$confirm" == "y" ]; then
            rm -f "${cfg_file}"
            action_die "removed '${target}'" 0
        else
            action_die "not removing '${target}'" 0
        fi
    else
        action_die "target not found: '${target}'"
    fi
}

setup

require action
require xdg

main "$@"
