#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
require action
require files
require process
require network

_show() {
    local name val
    name="$1"
    val="$2"
    printf "%25s: %s\n" "${name}" "${val}"
}

main() {
    local a master_ip
    files_load_config config config/cluster
    _show "Cluster name" "${cw_CLUSTER_name}"
    _show "Cluster UUID" "${cw_CLUSTER_uuid}"

    if [ -r "${cw_ROOT}"/etc/config/cluster/auth.rc ]; then
        files_load_config auth config/cluster
        _show "Cluster security token" "${cw_CLUSTER_auth_token}"
    fi

    if [ "${cw_INSTANCE_role}" == "master" ]; then
        master_ip="$(network_get_iface_address ${cw_CLUSTER_iface:-$(network_get_first_iface)})"
    elif [ "${cw_CLUSTER_master}" ]; then
        master_ip="${cw_CLUSTER_master}"
    else
        master_ip="none (autodetect)"
    fi
    _show "Master node IP address" "${master_ip}"
}

if sudo -l | grep -q ' ALL$'; then
    process_reexec_sudo
fi

main "$@"
